#.github/workflows/deploy.yaml
name: OnlineBiz
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: 'terraform'
    needs: [notify_start]
    env:
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy QA
        uses: reggionick/s3-deploy@v3
        with:
          folder: .
          bucket: '${{ secrets.S3_BUCKET }}'
          bucket-region: '${{ secrets.S3_BUCKET_REGION }}'
          delete-removed: true
          no-cache: true
          private: true
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ${{ env.AWS_REGION }}
      - name: 'Init'
        run: |
          terraform init
        working-directory: deploy/03-prd.labs.qcx.com/01-repository
      - name: 'Terraform apply'
        run: |
          terraform apply -var-file="../terraform/terraform.tfvars" -auto-approve
        working-directory: terraform        