name: IaC, Build & deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    # needs: [brakeman,rubocop,unit_tests]
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: 'Init'
        run: |
          terraform init -upgrade
        working-directory: terraform
      - name: 'Terraform apply'
        run: |
          terraform apply -var-file="terraform.tfvars" -auto-approve
        working-directory: terraform
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cache modules
  #       uses: actions/cache@v1
  #       id: yarn-cache
  #       with:
  #         path: website
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region:us-west-2
  #     - name: Use Node.js 12.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Build
  #       run: yarn build
  #     - name: Deploy
  #       run: aws s3 sync ./website s3://onlinebiz.com.br